# -*- coding: utf-8 -*-
"""HRV_Artifact_Detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zXV0_-qxtQbJpMEnyNWwQjHY_upcuIHK

# Artifact Detection HRVBio

## Loading Data
"""

# Cargamos datos
import pandas as pd

df = pd.read_excel(
    "/content/datos_long.xlsx")

df.head()

df.describe()

df["hr"] = 60000/df["rr"]

df.head()

"""# Preprocessing
## Artifact Detection

Removing artifacts using an adaptative thresholding RR value based on moving average.

INPUT:
*   RRs in ms
*   Threshold value
*   Sampling frequency

OUTPUT:
*   Corrected RR
*   Artifact index
*   Total artifacts
"""

import numpy as np

def artifact_correction_jr(rr, threshold = 4.3, fs = 1000):
    rr = np.array(rr, dtype=np.float64)
    der = np.abs(np.diff(rr)) #successive differences
    nac = np.where(der > threshold * np.std(rr))[0] + 1 #array of indexes, +1 because der is 1 index shorter

    rrc = rr.copy()
    rrc[nac] = np.nan

    # Linear Interpolation
    valid = ~np.isnan(rrc)
    rrc = np.interp(np.arange(len(rrc)), np.flatnonzero(valid), rrc[valid])

    nart = len(nac)


    return {
        "array corrected values": rrc,
        "index artifacts": nac,
        "number of artifacts": nart,
        #"array absolute differences": der
    }

df_001_s1 = df[(df["Participante"] == 1) & (df["Sesion"] == "s1")]
df_001_s1.head()

artifact_correction_jr(df_001_s1["rr"])

df_artifact = df.groupby(["Participante", "Sesion", "resp"]).apply(lambda x: artifact_correction_jr(x["rr"]))

df_artifact.to_excel("df_artifact.xlsx")